---

- name: Ensure aufs is installed
  apt:
    pkg: "linux-image-extra-{{ ansible_kernel }}"
    state: present
    update_cache: yes
  when: not ci

- name: Ensure we can use the https transport for apt-get
  apt: name=apt-transport-https update_cache=yes state=present

- name: Add Docker signing key
  apt_key: id=A88D21E9 keyserver=keyserver.ubuntu.com state=present

- name: Add Docker debian repository
  apt_repository: repo='deb https://get.docker.io/ubuntu docker main' state=present

- name: Install Docker
  apt: name=lxc-docker update_cache=yes state=present