- name: Pull Django docker image
  shell: docker pull helicopter88/klee_django

- name: Copy admin password script
  template: src=admin_psw.sh.j2 dest=/src/web/admin_psw.sh

- name: Get bower dependencies
  shell: bower install --config.interactive=false
  become: yes
  become_user: klide
  args:
    chdir: "{{ src_dir }}"
    executable: /bin/bash
  when: not ci

- name: Run grunt
  shell: grunt
  become: yes
  become_user: klide
  args:
    chdir: "{{ src_dir }}"
    executable: /bin/bash
  when: not ci

- name: Get bower dependencies
  command: bower install --config.interactive=false
  become: no
  args:
    chdir: "{{ src_dir }}"
  when: ci|bool

- name: Run grunt
  command: grunt
  become: no
  args:
    chdir: "{{ src_dir }}"
  when: ci|bool

- name: Run Django from docker
  shell: docker run -d --net="host" -v /tmp:/tmp -v /titb/src/static:/opt/static helicopter88/klee_django 
