- name: Pull Django docker image
  shell: docker pull helicopter88/klee_django:{{ docker_var }}

- name: Run Django from docker
  shell: docker run -d --net="host" -v /tmp:/tmp -v /titb/src/static:/opt/static helicopter88/klee_django:{{ docker_var }}
