- name: Create a nginx container
  command: docker create -p 80:80 -v /tmp:/tmp --name klee_nginx nginx

- name: Make a temporary folder for nginx files
  file: name=/nginx state=directory

- name: Configure nginx
  template: src=nginx.conf.j2 dest=/nginx/nginx.conf

- name: Configure nginx for the app
  template: src=sites-available_titb.conf.j2 dest=/nginx/default.conf group=www-data owner=www-data force=yes

- name: Copy the confing for nginx
  command: docker cp /nginx/nginx.conf klee_nginx:/etc/nginx/nginx.conf

- name: Copy the default website for nginx
  command: docker cp /nginx/default.conf klee_nginx:/etc/nginx/conf.d/default.conf
  
- name: Restart nginx
  command: docker start klee_nginx
